services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oj_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
